---
- hosts: default
  vars:
    admin_user: myadmin
    home_user: vagrant
  remote_user: "{{home_user}}"
  sudo: True
  tasks:
  - name: ensure apache is at the latest version
    user: name={{admin_user}} createhome=yes system=yes state=present
  - name: configure sudoers
    lineinfile: "dest=/etc/sudoers backup=yes state=present regexp='^%{{admin_user}}' insertafter='^# %wheel' line='%{{admin_user}} ALL=(ALL) NOPASSWD: ALL'"
  - file: path=/home/{{admin_user}}/.ssh state=directory owner={{admin_user}} group={{admin_user}} mode=700
  - name: Copy authorized_keys
    shell: cp /home/{{home_user}}/.ssh/authorized_keys /home/{{admin_user}}/.ssh/
  - name: install curl
    yum: name=curl-devel state=latest
  - name: install git
    yum: name=git state=latest
  - name: install mysql
    yum: name=mysql-devel state=latest
